### ISSUE TITLE
No tecnichal debt index result

### ISSUE THREAD

**Issue by SimonLollamen** [sonargraph/sonar-sonargraph-integration#13]
Hi,
i have installed and executed Sonarcube version 6.7.3 and also installed from the marketplace this plugin for calculate the SDI e SDC from sonargrapgh to sonarcube.
I put from the general system selection the plugin as default for all my java project

![image](https://user-images.githubusercontent.com/41190308/42687620-a8c5a488-8699-11e8-91c0-642192fa63d9.png)

The problem is that after i execute any project with this default settings the Debt index is no calculated, is always 0, instead with the settings of Sonarcube without the plugin i get the value
I follow the guide but i don’t understand why it doesn’t work.
Someone can help me?

Many thanks

Simone

**Comment by andreashoyerh2m** [comment]
Hello,
I assume "SDI" and "SDC" are used as abbreviations for "Structural Debt Index (Packages)" and "Structural Debt Index (Components)", which are metrics calculated by Sonargraph. When "Sonargraph Integration" is the profile of your project, you should see the values for SDI and SDC in Sonarqube's project page below "Measures -> Sonargraph Integration":
![screen shot 2018-07-13 at 18 32 39](https://user-images.githubusercontent.com/10628571/42703193-1d0c81ae-86cc-11e8-893a-ca287fa0ab9f.png)
If all values are zero Sonargraph's Sonarqube plugin didn't run correctly, or didn't run at all.
For further investigation, can you please provide a screenshot of your projects measures regarding "Sonargraph Integration" like the one above, and the log output of your build system regarding Sonargraph's Sonarqube plugin.

Best Regards
Andreas
