### ISSUE TITLE
com.hello2morrow.sonargraph.integration.sonarqube.SonargraphSensor has unsatisfied dependency

### ISSUE THREAD

**Issue by baywet** [sonargraph/sonar-sonargraph-integration#15]
I recently updated from sonarqube 7.4 to 7.6, and to version 2.1.7 for sonargraph (I don't know from which version though).
Some of our builds are now failing with the following error message:
```
com.hello2morrow.sonargraph.integration.sonarqube.SonargraphSensor has unsatisfied dependency 'class org.sonar.api.profiles.RulesProfile' for constructor 'public com.hello2morrow.sonargraph.integration.sonarqube.SonargraphSensor(org.sonar.api.batch.fs.FileSystem,org.sonar.api.profiles.RulesProfile,org.sonar.api.batch.measure.MetricFinder)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@5a67e962:116<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@df6620a:569<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@396ef8b2:60<|
```

**Comment by ingmarkellner** [comment]
Hi Vincent,
thanks for letting us know. We'll need to check which API got deprecated and will provide a new release asap.
Regards
Ingmar

**Comment by ingmarkellner** [comment]
A couple of other plugins suffer(ed) from the same problem: https://community.sonarsource.com/t/unsatisfied-dependency-in-sq-7-6/6244

I just published a pre-release for the Sonargraph plugin 3.1.0.
An official release will follow in the next couple of days. Please note that support for modules and directories have been dropped in SonarQube 7.6

**Comment by marcofranssen** [comment]
When will this be released? We are facing the same for all our projects ATM.

**Comment by ingmarkellner** [comment]
Thanks for the reminder!
I requested the official release: https://community.sonarsource.com/t/new-release-sonargraph-plugin-3-1-0/7913

**Comment by marcofranssen** [comment]
It seems there is a response on the forum with some concern regarding your PR.
