### ISSUE TITLE
Plugin execution fails on SonarQube 8.0, 8.1

### ISSUE THREAD

**Issue by ingmarkellner** [sonargraph/sonar-sonargraph-integration#19]
No measures and issues are imported when plugin is executed on SonarQube 8.
2019.11.13 12:35:14 INFO  ce[AW5ki8D8z__fqqKsR-lQ][o.s.c.t.s.ComputationStepExecutor] Compute cross project duplications | status=SUCCESS | time=0ms
2019.11.13 12:35:14 ERROR ce[AW5ki8D8z__fqqKsR-lQ][c.h.s.i.s.SonargraphBase] Sonargraph Integration: Failed to load built in meta data from '/com/hello2morrow/sonargraph/integration/sonarqube/ExportMetaData.xml' - Failure: Load data from stream
Error - Read Error. Failed to initialize JAXB
2019.11.13 12:35:14 INFO  ce[AW5ki8D8z__fqqKsR-lQ][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Webhooks | globalWebhooks=0 | projectWebhooks=0 | status=SUCCESS | time=5ms
2019.11.13 12:35:14 ERROR ce[AW5ki8D8z__fqqKsR-lQ][o.s.c.t.CeWorkerImpl] Failed to execute task AW5ki8D8z__fqqKsR-lQ
java.lang.NullPointerException: null
	at com.hello2morrow.sonargraph.integration.sonarqube.SonargraphMetrics.getMetrics(SonargraphMetrics.java:78)

Seems that the XML processing does not work as expected in Sonargraph Integration Access library

**Comment by chrisgahlert** [comment]
It seems like the problem is caused by the schema used in the `ExportMetaData.xml` file:

```
<ns3:exportMetaData xmlns:ns3="http://www.hello2morrow.com/sonargraph/core/export" xmlns:ns2="http://www.hello2morrow.com/sonargraph/core/report" ...>
```

The URL refrenced here is now returning a 404: http://www.hello2morrow.com/sonargraph/core/export

**Comment by ingmarkellner** [comment]
Hi Chris,
thanks for your thoughts.
But I think the root of the problem is something else. The same plugin works fine on SonarQube 7.9.1 but fails on SonarQube 8. I asked a question on the forum (https://community.sonarsource.com/t/java-security-accesscontrolexception-access-denied-java-lang-runtimepermission-createclassloader-on-sonarqube-8/16763) but did not receive an answer so far. :-(
There are similar bug reports and my hope is that the issue is fixed in SonarQube 8.1. 

BTW, xmlns URIs don't have to be retrievable: https://stackoverflow.com/questions/27613891/must-an-xml-namespace-name-uri-be-retrievable

**Comment by chrisgahlert** [comment]
Hi @ingmarkellner,

I thought so as well. But for us the problem started occuring when we restarted the Sonarqube server on Nov 26. (Before that the last restart was on Nov 20.)

As we run the server inside a Docker container and haven't changed anything since, I figured it had to be caused by some external factors.

But I'm curious to know the root cause of this! :)

**Comment by thomas-eaa** [comment]
Hi! Does this mean you're not further investigating the issue until SonarQube 8.1 will be released?

**Comment by ingmarkellner** [comment]
Hi @thomas-eaa,
I pinged again on the SonarQube forum, and I don't have an idea about what else to do...
Feel free to leave a note on the forum, too, so that might increase the importance for SonarQube developers to provide an answer.
Sorry, there is not much we can do about it otherwise at the moment, but I am open for suggestions.

**Comment by ingmarkellner** [comment]
Unfortunately, there is no difference in SonarQube 8.1 and I haven't got any feedback to my question on the forum. :-( 
I will try to work around that issue...

**Comment by ingmarkellner** [comment]
No luck, there seems to exist a fundamental problem with creating classloaders in SQ8.0 and newer. This prevents working with the used XML library, so there is no easy workaround for us.
I posted another question in the forum: https://community.sonarsource.com/t/access-denied-java-lang-runtimepermission-getclassloader-for-plugin-in-computing-engine-of-sq-8-0-and-sq-8-1/17916
Hopefully, this will get more attention than the previous post.

**Comment by ingmarkellner** [comment]
If there is no solution at the beginning of the new year, I will bite the bullet and implement the info retrieval differently. Just feels like a waste of time, fixing something that has been working and that someone else is responsible for... Well that's life, I suppose. :-/

**Comment by ingmarkellner** [comment]
Finally, I got a response. Usage of classloaders is not allowed for plugins on the server side in SQ8.0 and newer. Thus, I need to refactor.

**Comment by thomas-eaa** [comment]
Ok, thank you. We're waiting for the new release of your plugin then. Good luck!

**Comment by ingmarkellner** [comment]
I implemented a fix and tested it successfully with my local SonarQube 8.1 instance.
A new release has been created and it is available here at GitHub or via our download site https://www.hello2morrow.com/products/downloads

**Comment by thomas-eaa** [comment]
Looks good, tested with SonarQube 8.0.
