### ISSUE TITLE
Improvement: Determine path to sonargraph-report relative to module base-dir

### ISSUE THREAD

**Issue by Argelbargel** [sonargraph/sonar-sonargraph-integration#2]
Hi there,

if the path given via the property `sonar.sonar_integration.report.path` is relative (e.g. does not start with an `/`, then the plugin should try to determine the path to the report-file relative to the current module's baseDir to support a multi-module configuration.

For example, with this sonar-project.properties:

``` sonar.projectKey=myProject
sonar.modules=module1,module2
sonar.sonargraph_integration.report.path=build/sonargraph/sonargraph-sonarqube-report.xml
module2.sonar.projectBaseDir=custom/path/to/module2
```

the plugin should search the report-file for module1 at `module1/build/sonargraph/sonargraph-sonarqube-report.xml` and for module2 at `custom/path/to/module2/build/sonargraph/sonargraph-sonarqube-report.xml`.

Kind regards

Argelbargel

**Comment by ingmarkellner** [comment]
Verified.
